### ISSUE TITLE
error Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by nvjacobo** [Automattic/_s#1446]
Hi, 

I am trying to use _s

$npm instal 

```
3761 verbose stack     at /usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
3761 verbose stack     at runMicrotasks (<anonymous>)
3761 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
3762 verbose cwd /home/jacobo/_s
3763 verbose Linux 4.19.0-9-amd64
3764 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
3765 verbose node v12.18.2
3766 verbose npm  v6.14.6
3767 error Unexpected end of JSON input while parsing near '...a":"^2.5.3"},"dist":{'
3768 verbose exit [ 1, true ]
```

My system 

- npm 6.14.6
- node v12.18.2
- system Debian Buster 10 

Thanks, Jacobo

**Comment by Ismail-elkorchi** [comment]
Hi, @nvjacobo ! This issue was just fixed with https://github.com/Automattic/_s/pull/1516.

**Comment by nvjacobo** [comment]
Thanks @Ismail-elkorchi!
