### ISSUE TITLE
Console error while compiling the css - Underscores theme

### ISSUE THREAD

**Issue by Marc-MMA** [Automattic/_s#1479]
Hello, I run the command `npm run compile:css` after having scrupulously followed the documentation and I have an error

![image](https://user-images.githubusercontent.com/48863685/104642037-7f7e9b00-5678-11eb-970f-f7bc57a3a809.png)

This is what my log file says 2021-01-14T19_50_43_085Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile:css'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'precompile:css', 'compile:css', 'postcompile:css' ]
5 info lifecycle underscores@1.0.0~precompile:css: underscores@1.0.0
6 info lifecycle underscores@1.0.0~compile:css: underscores@1.0.0
7 verbose lifecycle underscores@1.0.0~compile:css: unsafe-perm in lifecycle true
8 verbose lifecycle underscores@1.0.0~compile:css: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\mma_demo\wp-content\themes\mma\node_modules\.bin;C:\Users\Marc\Desktop\cmder\vendor\bin;C:\Users\Marc\Desktop\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\Marc\Desktop\cmder\vendor\conemu-maximus5;C:\Users\Marc\Desktop\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\xampp\php;C:\composer;C:\Program Files\Git\cmd;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Users\Marc\AppData\Local\Yarn\bin;C:\Users\Marc\AppData\Roaming\npm;C:\Users\Marc\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Marc\Desktop\cmder
9 verbose lifecycle underscores@1.0.0~compile:css: CWD: C:\xampp\htdocs\mma_demo\wp-content\themes\mma
10 silly lifecycle underscores@1.0.0~compile:css: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   "node-sass sass/ -o ./ && stylelint '*.css' --fix || true && stylelint '*.css' --fix"
10 silly lifecycle ]
11 silly lifecycle underscores@1.0.0~compile:css: Returned: code: 1  signal: null
12 info lifecycle underscores@1.0.0~compile:css: Failed to exec compile:css script
13 verbose stack Error: underscores@1.0.0 compile:css: `node-sass sass/ -o ./ && stylelint '*.css' --fix || true && stylelint '*.css' --fix`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid underscores@1.0.0
15 verbose cwd C:\xampp\htdocs\mma_demo\wp-content\themes\mma
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:css"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error underscores@1.0.0 compile:css: `node-sass sass/ -o ./ && stylelint '*.css' --fix || true && stylelint '*.css' --fix`
22 error Exit status 1
23 error Failed at the underscores@1.0.0 compile:css script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

I can't debug, my skills are limited. Thanks

**Comment by LukeVibes** [comment]
I get the same error :(

Any luck?

**Comment by sproutient** [comment]
Same error for me too...

**Comment by sproutient** [comment]
This seems to help : https://github.com/Automattic/_s/issues/1467

**Comment by Ismail-elkorchi** [comment]
Hi, everyone ! I have just updated the npm packages (https://github.com/Automattic/_s/pull/1516), which seems to resolve the issues reported here.
